name: lint-github-workflows
description: Lint GitHub workflow files using Prettier

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - ".github/**"
  pull_request:
    paths:
      - ".github/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false

      - name: Run Prettier on .github workflow files
        run: |
          npx prettier --check .github/
